name: Main branch tests

permissions:
  contents: read

on:
  push:
    branches: ['main']

jobs:

  platform-tests:
    uses: ./.github/workflows/platform-tests.yml

  scorecard:
    uses: ./.github/workflows/scorecard.yml

  basic-downstream:
    uses: ./.github/workflows/downstream-basic.yml
