name: Linux tests

permissions:
  contents: read

on: [workflow_call, workflow_dispatch]

jobs:

  linux:
    strategy:
      fail-fast: false
      matrix:
        # total of 38 test runs here.
        runner: [ubuntu-latest, oqs-arm64]
        # Test all combinations of the following options.
        # Generates 16 base test runs (4 on arm, 4 on x86_64).
        compiler: [gcc, clang]
        shared: [ON, OFF]
        openssl: [ON, OFF]
        # Default values to be overridden selectively
        sha3-openssl: [OFF]
        dlopen-openssl: [OFF]
        dist-build: [ON]
        opt-target: [auto]
        stfl: [OFF]
        stfl-keygen: [OFF]
        libjade: [OFF]
        build-options: ['']
    runs-on: ${{ matrix.runner }}
    container:
      image: openquantumsafe/ci-ubuntu-latest:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4
      - name: Configure
        run: |
          mkdir build && cd build && \
          cmake -GNinja -DOQS_STRICT_WARNINGS=ON \
            -DCMAKE_C_COMPILER=${{ matrix.compiler }} \
            -DBUILD_SHARED_LIBS=${{ matrix.shared }} \
            -DOQS_USE_OPENSSL=${{ matrix.openssl }} \
            -DOQS_USE_SHA3_OPENSSL=${{ matrix.sha3-openssl }} \
            -DOQS_DLOPEN_OPENSSL=${{ matrix.dlopen-openssl }} \
            -DOQS_DIST_BUILD=${{ matrix.dist-build }} \
            -DOQS_OPT_TARGET=${{ matrix.opt-target }} \
            -DOQS_OPT_TARGET=${{ matrix.opt-target }} \
            -DOQS_ENABLE_SIG_STFL_LMS=${{ matrix.stfl }} \
            -DOQS_ENABLE_SIG_STFL_XMSS=${{ matrix.stfl }} \
            -DOQS_HAZARDOUS_EXPERIMENTAL_ENABLE_SIG_STFL_KEY_SIG_GEN=${{ matrix.stfl-keygen }} \
            -DOQS_LIBJADE_BUILD=${{ matrix.libjade }} \
            ${{ matrix.build-options }} .. && \
          cmake -LA -N ..
      - name: Build
        run: ninja
        working-directory: build
